### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by forcex450** [Reponse-App/reponse.db#1]
https://github.com/Reponse-App/reponse.db/blob/0a12d8025c3f054db474713cd8539b3425c0a53c/index.js#L13

First of all, it is very funny that you write such a database. How will people connect to the localhost you have opened?, then I recommend you to look at how the database is written.

**Comment by aloshai** [comment]
it's a new technology, you wouldn't understand.

**Comment by aloshai** [comment]
now we can communicate with the servers through the mind.

**Comment by aloshai** [comment]
for example;

```js

```

**Comment by aloshai** [comment]
I want to turn into a potato. What can I do for it? Of course I'll send a imaginary request to the server.
.
.
.
I'm a potato now.

**Comment by benerenla** [comment]
> It's a new technology, you wouldn't understand. Now we can communicate with the servers through the mind.
> 
> I want to turn into a potato. What can I do for it? Of course I'll send a imaginary request to the server. . . . I'm a potato now.

I love potatoes very much. Instead of scolding, you can contribute a little to the nation.

**Comment by aloshai** [comment]
Firstly, I didn't scold anyone. I was just kidding.

Secondly, I was planning to do throw PR to help you but I couldn't make sense of anything about how it works project.

**Comment by benerenla** [comment]
Projedeki amacım başka vds'e database yazdirmakti ve aklıma istekler kullanarak yapmak geldi post ve get işlemlerini vds de yakalayıp vds e data yazdırıyorum yanlış anlamışım kusura bakma

**Comment by Drackin** [comment]
> 

This database for Reponse VDS machine. We want to share this package's source code. Please don't speak without knowing :))) because you don't look cool you look ignorant

**Comment by aloshai** [comment]
Farklı makinelere veri aktarımı yapmak için tabii ki bağlantı kurman gerekirdi. Ben projeyi incelerken `URL` olarak tanımladığınız şeyin boş olmasını pek anlayamamıştım. Aslında sadece bu değil, birçok şeye anlam verememiştim. Asıl ben özür dilerim sizi kırmak ya da rencide etmek istemedim. 

Size birkaç tavsiyede bulunabilirim:
Reponse.db modülünü bana kalırsa yerel olarak çalıştırın. Yani gerek bir dosya ya da gerek bir veri tabanı dili/programı ile yapın çünkü farklı bir yerlere istek attırmak pek mantıklı bir iş değil. *Tabii ki her zaman mantıksız değil, bazen kapsamlı ve birden fazla istemcinin/sunucunun bulunduğu projelerde ana veri tabanı sunucusunun bulunması mantıklıdır.* Yerel olarak çalışması daha iyi olur. İnsanlar istediği zaman sizin modülünüzü kullanarak bu modül için bir endpoint yapabilirler. Hem insanlar yerel olarak bu modülü kullanmak isterlerse rahat bir şekilde kullanabilirler.

**Comment by benerenla** [comment]
amacımız zaten kendimize ozel çalıştırmaktı :)
